import { test, expect } from '@playwright/test';
import { expectNoConsoleErrors } from '../../helpers';

// PWA prod sanity layer: validates the deployed build's manifest, service
// worker scope, asset reachability, and console silence. These checks only
// make sense against a real subpath deployment (e.g.
// https://roomi-fields.com/kanopi/) because:
//  - the manifest's start_url/scope embed the build-time VITE_BASE_PATH
//    (defaults to "/" in dev, "/kanopi/" only for npm run build:prod);
//  - the service worker is generated by vite-plugin-pwa at build time and
//    isn't served by `npm run dev`;
//  - assets resolve under /kanopi/assets/* with hashed names only in the dist.
//
// Therefore every test below skips when KANOPI_BASE_URL is unset or points to
// a localhost dev server. Run it via `npm run e2e:prod` (which sets
// KANOPI_BASE_URL=https://roomi-fields.com/kanopi/).

const baseURL = process.env.KANOPI_BASE_URL ?? '';
const isProd = baseURL !== '' && !baseURL.includes('localhost');

test.describe('PWA prod sanity', () => {
  test.skip(!isProd, 'requires KANOPI_BASE_URL pointing to a non-localhost deployment');

  test('manifest.webmanifest is served with the correct Content-Type', async ({ request }) => {
    const res = await request.get('manifest.webmanifest');
    expect(res.status()).toBe(200);
    // Some hosts append a charset suffix (e.g. "application/manifest+json;
    // charset=utf-8"). Accept any value that starts with the canonical type.
    const contentType = res.headers()['content-type'] ?? '';
    expect(contentType.toLowerCase()).toContain('application/manifest+json');
  });

  test('manifest start_url and scope both end with /kanopi/', async ({ request }) => {
    const res = await request.get('manifest.webmanifest');
    expect(res.status()).toBe(200);
    const manifest = (await res.json()) as { start_url?: string; scope?: string };
    expect(manifest.start_url, 'manifest.start_url').toBeDefined();
    expect(manifest.scope, 'manifest.scope').toBeDefined();
    expect(manifest.start_url!.endsWith('/kanopi/')).toBe(true);
    expect(manifest.scope!.endsWith('/kanopi/')).toBe(true);
  });

  test('service worker is registered with a /kanopi/ scope', async ({ page }) => {
    await page.goto('/');
    // vite-plugin-pwa registers the SW from main.ts via registerSW() after the
    // shell mounts. Give it a moment — the registration is async and the
    // service worker file itself is fetched in the background.
    const scope = await page.waitForFunction(
      async () => {
        if (!('serviceWorker' in navigator)) return null;
        const reg = await navigator.serviceWorker.getRegistration();
        return reg ? reg.scope : null;
      },
      undefined,
      { timeout: 15_000 }
    );
    const scopeValue = (await scope.jsonValue()) as string | null;
    expect(scopeValue, 'navigator.serviceWorker.getRegistration().scope').not.toBeNull();
    expect(scopeValue!.endsWith('/kanopi/')).toBe(true);
  });

  test('all script src and stylesheet href elements resolve to HTTP 200', async ({ page }) => {
    await page.goto('/');
    // Wait for the shell so we know the index has fully parsed and any
    // dynamically inserted asset links (preload, modulepreload) are present.
    await expect(page.getByText('KANOPI').first()).toBeVisible({ timeout: 15_000 });

    // Resolve every src/href against the document base so relative paths
    // (./assets/foo.js) and absolute ones (/kanopi/assets/foo.css) both land
    // on a fully-qualified URL the request fixture can HEAD.
    const urls = await page.evaluate(() => {
      const out: string[] = [];
      document.querySelectorAll<HTMLScriptElement>('script[src]').forEach((s) => {
        if (s.src) out.push(s.src);
      });
      document.querySelectorAll<HTMLLinkElement>('link[rel="stylesheet"][href]').forEach((l) => {
        if (l.href) out.push(l.href);
      });
      return out;
    });

    expect(
      urls.length,
      'expected at least one script or stylesheet in the document'
    ).toBeGreaterThan(0);

    const failures: { url: string; status: number }[] = [];
    for (const url of urls) {
      const res = await page.context().request.head(url);
      if (res.status() !== 200) {
        failures.push({ url, status: res.status() });
      }
    }
    expect(failures, `non-200 assets: ${JSON.stringify(failures)}`).toEqual([]);
  });

  test('no browser console errors in the first 5 seconds after load', async ({ page }) => {
    const assertNoErrors = expectNoConsoleErrors(page);
    await page.goto('/');
    await expect(page.getByText('KANOPI').first()).toBeVisible({ timeout: 15_000 });
    // Five-second observation window per spec — long enough for deferred
    // adapter imports and the service worker fetch to surface any errors.
    await page.waitForTimeout(5000);
    assertNoErrors();
  });
});
